name: Auto Merge PR

on:
  pull_request_review:
    types: [submitted]

jobs:
  automerge:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: write
    steps:
      - name: Auto-merge approved PR
        uses: ahmadnassri/action-auto-merge@v2.0.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          merge-method: squash # ou merge/rebase
          delete-branch: true
